name: flight
version: 0.0.3
description: A modern, lightweight, extensible framework for creating rich APIs in Dart.
author: Bradley Watton <mail@bradleyw.me>
homepage: https://github.com/HypertextPP/Flight
repository: https://github.com/HypertextPP/Flight
issue_tracker: https://github.com/HypertextPP/Flight/issues

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  body_parser: ^1.1.1
  http_parser: 3.1.3

dev_dependencies:
